# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pod_discovery_pb2 as pod__discovery__pb2


class PodDiscoveryStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPod = channel.unary_unary(
        '/com.symphony.service.poddiscovery.grpc.PodDiscovery/GetPod',
        request_serializer=pod__discovery__pb2.PodName.SerializeToString,
        response_deserializer=pod__discovery__pb2.Pod.FromString,
        )
    self.ListPods = channel.unary_stream(
        '/com.symphony.service.poddiscovery.grpc.PodDiscovery/ListPods',
        request_serializer=pod__discovery__pb2.ListPodRequest.SerializeToString,
        response_deserializer=pod__discovery__pb2.Pod.FromString,
        )


class PodDiscoveryServicer(object):
  """Interface exported by the server.
  """

  def GetPod(self, request, context):
    """Obtain extensive details of a Pod based on Vanity name.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPods(self, request, context):
    """A server-to-client streaming RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PodDiscoveryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPod': grpc.unary_unary_rpc_method_handler(
          servicer.GetPod,
          request_deserializer=pod__discovery__pb2.PodName.FromString,
          response_serializer=pod__discovery__pb2.Pod.SerializeToString,
      ),
      'ListPods': grpc.unary_stream_rpc_method_handler(
          servicer.ListPods,
          request_deserializer=pod__discovery__pb2.ListPodRequest.FromString,
          response_serializer=pod__discovery__pb2.Pod.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.symphony.service.poddiscovery.grpc.PodDiscovery', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
